# Generated by Django 5.2.5 on 2025-08-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_data'),
    ]

    operations = [
    ]
